export const dogBreedOptions = [
  'Aspin',
  'Aspin Mix',
  'Labrador Retriever',
  'Labrador Mix',
  'Golden Retriever',
  'Golden Retriever Mix',
  'German Shepherd',
  'German Shepherd Mix',
  'Shih Tzu',
  'Pomeranian',
  'Chihuahua',
  'Beagle',
  'Siberian Husky',
  'Husky Mix',
  'Poodle',
  'Poodle Mix',
  'Dachshund',
  'Corgi',
  'Rottweiler',
  'Border Collie',
  'Jack Russell Terrier',
  'Belgian Malinois',
  'Boxer',
  'Doberman',
  'Other',
] as const

export const catBreedOptions = [
  'Puspin',
  'Puspin Mix',
  'Persian',
  'Siamese',
  'Maine Coon',
  'British Shorthair',
  'Scottish Fold',
  'Bengal',
  'Sphynx',
  'Ragdoll',
  'Russian Blue',
  'Other',
] as const
